Fix #106 change
NanyaTK/255_RPRO pull request #107
Opened 2024-10-27 13:11 UTC by Sopuranoaruto

10/27の朝から晩までやってましたが、最後で躓いているので助けてほしいです。
1つ前にコミットしたものでidは変更できて、同じものが複数あると一番前のものしか欠席回数が変化しない状態になった。
そこから調べながらやってabsenceCountのところをクラスにしたらできそうだと思ったが、試行錯誤してもうまく行かず、最も良かったものがいま最新のもの(表記は変わらないがlocalStrage上では変化しており、再起動でのリセットなどでもプログラムが止まらない状態)
また、idが教科になった都合上、削除の際にプログラムが引っかかるのを防ぐため、とりあえずで0~100までのid分リセットするようになっている。

2024-10-27 15:40 UTC, Sopuranoaruto commented
多分行けています。
作業で書き直しているうちにいつの間にか巻き込まれて消えていた部分があったみたいです。

2024-10-28 01:29 UTC, amedama-tech approved these changes
Ok

2024-10-28 04:58 UTC, NanyaTK requested changes
localstorage のkeyは削除

2024-10-30 08:37 UTC, NanyaTK approved these changes
OK
v1.4.3でPRだします

2024-10-30 08:37 UTC, merged