Feat #14 時間割表示機能作成
NanyaTK/255_RPRO pull request #31
Opened 2024-08-23 09:06 UTC by amedama-tech

ローカルに保存する概念が終わっているので、今後障害を及ぼすかもしれません

2024-08-23 09:12 UTC, NanyaTK commented
@amedama-tech 
22時までにテストサーバでテストした後マージするので実装機能について書いていてください

2024-08-23 12:16 UTC, NanyaTK requested changes
テストサーバを参照すればわかるように，ユーザのリクエストに対してサーバはファイルの読み取りをセキュリティ上の観点から許可していない．
index.phpに修正が必要です．
要はmain,phpでjsのlocalstrageに保存したデータをphpにサーバのファイルを経由せず，ユーザのみで渡す必要があります．

2024-08-23 12:16 UTC, NanyaTK commented on src/index.php
l5．サーバのファイルを読み取ろうとしているが，ここではユーザのローカルデータ（localstrage）を読み取るべきである

2024-08-24 14:12 UTC, Sopuranoaruto approved these changes, later dismissed

2024-08-31 14:27 UTC, NanyaTK approved these changes

2024-08-31 14:28 UTC, amedama-tech commented
新しい時間割を登録するボタン(119行目)に新機能として、"phpへ値を渡す"を実装したので、それに伴うphp文を追加しました。(1行~8行)
それに伴って、index.phpを削除。
また、subjects.jsonも削除。
新しい時間割を登録するボタンに新機能として、JSで値を設定する隠しフィールドを実装しました。(116行~120行)
AJAXで行っていた通信に関するプログラム削除し、新しくJSONデータを文字列にして隠しフィールドに設定するプログラム追加(153行~157行)
subjects.jsonで行っていた初期値設定を行う(167行~170行)

2024-08-31 14:30 UTC, NanyaTK commented
これリログしたらデータ反映できないです

2024-08-31 14:31 UTC, NanyaTK requested changes

2024-08-31 14:31 UTC, NanyaTK commented on src/main.php
リログしたときに隠しフィールドからもってくるコードが必要

2024-08-31 14:31 UTC, amedama-tech commented
リログってなに

2024-08-31 14:33 UTC, NanyaTK commented
再読み込みしたときのコードがいるかも
test.rpro.nanyatk.com
参照して，登録したらタブ閉じてもう一回アクセスしてみたらわかると思う

2024-08-31 14:37 UTC, amedama-tech commented
> 再読み込みしたときのコードがいるかも https://test.rpro.nanyatk.com 参照して，登録したらタブ閉じてもう一回アクセスしてみたらわかると思う

そか、現状のプログラムだとローカルストレージからの参照が、登録してくれた時にしかできてない判定ってことか

2024-09-07 16:37 UTC, amedama-tech commented
ぼくは力が無かったので、うんちくそくそプログラムを作成しました。
ロボット制御等で見かけるような、時間を用いたプログラム作成を行いました。何かしらの時間割のデータを有して、前回の更新時よりも時間があいて更新されている時に、時間割表示してください～っていうのを送信しなおすことで、リログ時にも時間割が反映できるようになったはずです。（244行～275行）

2024-09-08 00:58 UTC, NanyaTK approved these changes, later dismissed
問題ないと思います
@Sopuranoaruto 次のURLからもいろいろ試して問題ないか確認しといてください
https://test.rpro.nanyatk.com/main.php

2024-09-08 01:02 UTC, amedama-tech commented
> 問題ないと思います @Sopuranoaruto 次のURLからもいろいろ試して問題ないか確認しといてください https://test.rpro.nanyatk.com/main.php

写真黄色部分の文字って今後無くす予定なん？

![IMG_5058](https://github.com/user-attachments/assets/479d3da3-cee3-4c14-ad1f-f4ca14277bf3)

2024-09-08 01:03 UTC, NanyaTK commented
yes

2024-09-08 01:28 UTC, NanyaTK approved these changes, later dismissed

2024-09-08 01:29 UTC, NanyaTK approved these changes

2024-09-08 01:56 UTC, Sopuranoaruto commented
かずまが作ったところは多分大丈夫なんだけど、いま、新規登録で空きコマを変えるときの選択肢がコースで変わらなくて、4年のEDとEJの選択肢が一緒になって出てきているんだけど、これはバグ？それともこのあたりの機能が未実装なだけ？

2024-09-08 02:11 UTC, amedama-tech commented
> かずまが作ったところは多分大丈夫なんだけど、いま、新規登録で空きコマを変えるときの選択肢がコースで変わらなくて、4年のEDとEJの選択肢が一緒になって出てきているんだけど、これはバグ？それともこのあたりの機能が未実装なだけ？

未実装やと思う。今空きコマ選択するやつは、ただデータベースに存在してる教科を全部表示してるだけになっとると思う。

2024-09-08 02:41 UTC, NanyaTK commented
未実装ﾅﾘｹﾙ

2024-09-08 02:48 UTC, Sopuranoaruto commented
> > かずまが作ったところは多分大丈夫なんだけど、いま、新規登録で空きコマを変えるときの選択肢がコースで変わらなくて、4年のEDとEJの選択肢が一緒になって出てきているんだけど、これはバグ？それともこのあたりの機能が未実装なだけ？
> 
> 未実装やと思う。今空きコマ選択するやつは、ただデータベースに存在してる教科を全部表示してるだけになっとると思う。

了解です

2024-09-08 02:49 UTC, Sopuranoaruto approved these changes

2024-09-08 06:15 UTC, merged