Feat #23 delete
NanyaTK/255_RPRO pull request #96
Opened 2024-10-12 11:07 UTC by Sopuranoaruto

削除ボタンの実装
・f12ボタンでローカルストレージのデータが消えたのは確認できたが、
リロードしても時間割の部分が変わらないので、どこいじればいいか教えてほしいです。
・新規登録ボタンか削除ボタンのどちらかしか出ないようにしたが、最初の何回かロードするときに一瞬どっちも写ってた。
・一番上の問題の解決のめどがたったら削除実行する時の警告をもっと危険な操作だと分かるようにするつもりです(文字を赤色にするなど)。

2024-10-12 12:01 UTC, NanyaTK commented
ブランチを間違えています

2024-10-12 12:14 UTC, NanyaTK commented
> 削除ボタンの実装 ・f12ボタンでローカルストレージのデータが消えたのは確認できたが、 リロードしても時間割の部分が変わらないので、どこいじればいいか教えてほしいです。

ではデータなしでローカルストレージを上書きすればよいのではないでしょうか

2024-10-12 12:21 UTC, NanyaTK commented
addeventlistenerではなくonclickにした理由はありますか？

2024-10-12 12:43 UTC, Sopuranoaruto commented
いや特にないです
addeventlistenerの方がいいですか？

2024-10-12 13:24 UTC, NanyaTK commented
（可読性と拡張性の面で）そうですね
なんならその上のやつも変えといてほしいくらいです

2024-10-12 14:34 UTC, NanyaTK commented
このPRではleroadを使い，#49 にて非同期処理が追加されたら非同期処理に移行しましょう

2024-10-12 15:20 UTC, Sopuranoaruto commented
いろいろローカルストレージ上書きしたり、新規登録と似たような動作をさせたりしたんですけど直りません

2024-10-12 15:21 UTC, Sopuranoaruto commented
ローカルストレージ以外に保存されるようなところありますか

2024-10-12 23:56 UTC, NanyaTK commented
コミットしてもらわないと変更をこっちで追跡できないのでコミットしてください

2024-10-13 07:39 UTC, Sopuranoaruto commented
featつけるの忘れてた
あと、試すうちに消しちゃったけど、上で書いたとおり新規登録確定の部分をコピーして動作させてみたりもした。

2024-10-13 09:13 UTC, NanyaTK commented
動作を修正しました．確認してください．
また，意図的にdeleteAllCachesを組み込んだ理由はありますか？

2024-10-13 09:24 UTC, Sopuranoaruto commented
いやこれはいろいろ試す中で入れたやつ

2024-10-13 09:48 UTC, NanyaTK commented
テストサーバにデプロイしました
https://test.rpro.nanyatk.com/

2024-10-13 09:49 UTC, Sopuranoaruto commented
いけてそう
deleteAllCaches消したほうが良い？

2024-10-13 09:50 UTC, NanyaTK approved these changes

2024-10-13 09:50 UTC, NanyaTK commented on src/main.css
共通化をするべき -> 後に余裕があれば対応

2024-10-13 09:50 UTC, NanyaTK commented
> いけてそう deleteAllCaches消したほうが良い？

既に消してます

2024-10-13 09:57 UTC, Sopuranoaruto commented
> テストサーバにデプロイしました https://test.rpro.nanyatk.com/

自分でphpサーバーでやったらうまく行くんだけどこっちのリンクから飛ぶとバグってるんだけど他の人もなってる？

2024-10-14 07:43 UTC, NanyaTK commented
@Ris561 
テストサーバは既に別のブランチのテストとなったのでレビュー時の参考にしないでください

2024-10-14 07:54 UTC, NanyaTK commented
v1.3.8リリース後，テストサーバにて確認した後，v1.4.0 予定とします

2024-10-14 09:15 UTC, Ris561 approved these changes
okuretesuimasen

2024-10-14 09:19 UTC, NanyaTK requested changes
v1.3.9町

2024-10-14 09:21 UTC, Ris561 approved these changes
kokookok

2024-10-14 13:28 UTC, NanyaTK commented
私の修正が予想より大幅に増えたので一旦マージします

2024-10-14 13:28 UTC, NanyaTK approved these changes

2024-10-14 13:28 UTC, merged